### ISSUE TITLE
make-core-database fails

### ISSUE THREAD

**Issue by dgleks** [lisdude/toastcore#2]
When attempting to run make-core-database, the core extraction fails to complete and tracebacks on $wiz:mcd_2. I've done some digging and have managed to track this back to the map properties $options and $help_db. When removed, make-core-database completes successfully (aside from any errors in init_for_core verbs).

Further investigation leads me to believe that this could be stemming from #0:core_object_info. When running this verb, all the objects from the options and help_db properties are shown as they should be. However, when it comes to the property names, these props do not expand to show the key. E.G.: Instead of displaying {"options["prog"], "options["display"]} etc, you simply get something like: {"options", "options", "options"}.

Also, $proto and its children seem to not make it out alive when attempting to make-core-database. The properties on #0 for them still exist, but they are simply set to #-1.

**Comment by lisdude** [comment]
Hopefully everything is working now. MCP had some trouble too.

Thanks for the detailed report! It definitely helped find a starting place in those scary verbs.
