### ISSUE TITLE
Inline Editor: Bug with `/pass'

### ISSUE THREAD

**Issue by dgleks** [lisdude/toastcore#5]
The inline editor in ToastCore seems to have a bug with the `/pass' command. More specifically, `/pass' breaks when used by anyone other than the owner of $edit_utils (in this case Wizard). The bug in question causes any attempt to use `/pass' multiple times in a row to fail, and instead treats the command and provided arguments as a line to insert into the working text.

Steps to Reproduce:

1. Log in a character other than Wizard (programmer/wizard status is irrelevant).
2. Enter editor mode (using `@paste' or similar).
3. Attempt a `/pass' command (this should work).
4. Attempt a `/pass' command again (this time it should fail and instead insert the command and its arguments as a line in the working text).
5. This only happens when attempting to use `/pass' multiple times in a row; using it once then adding text and using it again does not present this issue.

I'm fairly-certain that this has something to do with permissions, since using `@transfer' to change ownership of $edit_utils to someone else nullifies the bug for the new owner, and introduces it for Wizard. This was tested from the latest commit of an unmodified ToastCore database and the latest commit of an unmodified ToastStunt server.
OS Used: Ubuntu 20.04 (tested with both WSL and native environments)

**Comment by dgleks** [comment]
Also before testing, you'll have to replace the $player_utils call in $edit_utils:cmd_pass with $command_utils and set $server_options.protect_force_input to 0, then call load_server_options(). Other than that though, no modifications were made to the database/server from their default state.

**Comment by distantorigin** [comment]
I was able to reproduce this with preliminary testing. At the very least, the $player_utils call in cmd_pass needs to be changed to $command_utils in the core, since that's a ChatMUD leftover.

**Comment by dgleks** [comment]
Yep! I forgot to mention making that change along with the setting of $server_options.protect_force_input to 0 and calling load_server_options() in my initial comment, so I included it in a follow-up comment. Sorry about that!
