### ISSUE TITLE
database seemingly not persisting?

### ISSUE THREAD

**Issue by zersiax** [lisdude/toastcore#6]
This is more than likely user error, but I don't really know where else to go with this.
When starting the moo like this:

./moo -p 1234 toastcore.db toastcore.db.new

Everything works great. I can connect, I can make all the changes in the universe. But, when the first dump happens, and when the server goes down, it seems to neatly store everything. Except, when I then use either toastcore.db or toastcor.db.new to subsequently restart the server, all modifications are gone and we're back to stock.
Is there some setting in-game I need to alter for that not to happen?

**Comment by distantorigin** [comment]
When restarting, are you flip-flopping the toastcore.db.new with toastcore.db? The first argument is the database to load; the second is the database to dump to. Thus, once you've dumped your database to toastcore.db.new, when restarting you'd want:

```./moo -p 1234 toastcore.db.new toastcore.db```

Also verify that the database is actually being written to by checking the modification time of toastcore.db.new.

Unless you have an explicit reason not to, my personal recommendation is to dump to the same database file that you're sourcing from; in other words, drop the .new and use the same database for both source and destination. If you really want to keep the originating database, commit it to a versioning system prior to startup. (YMMV.)

**Comment by zersiax** [comment]
I am flipping them, yes. I did not check if the database is being written to, I can use the same for both and see what that does though. What would prevent it to write to the db?

**Comment by distantorigin** [comment]
What does the log say when you dump the database?

**Comment by zersiax** [comment]
says its essentially dumping everything to toastcore.db.new#1# , not sure what the number indicates but there's no file in the folder with that name. I do see a .PANIC though.

**Comment by distantorigin** [comment]
The .PANIC file will be the saved copy. I'd look into why the server is panicking in the first place; are you shutting it down cleanly with a SIGINT or ```;shutdown()```?

**Comment by zersiax** [comment]
sigint, just a ctrl+c, which prints the dump log. It seems that using just one db fixes this though.
I will keep at it with just one db file and see if that makes a difference.
Possibly tangentially related as it's also seemingly to do with databases, but if I use  other dbs like jhcore or waterpoint I get the following error:
#25:domain_literal (this == #25), line 6:  Unknown built-in function
... called from #10:blacklisted graylisted redlisted (this == #10), line 9
... called from #0:do_login_command (this == #0), line 4
(End of traceback)

Is this related?

**Comment by distantorigin** [comment]
This traceback is almost certainly due to the deprecation of the tonum() builtin function in ToastStunt. Do a find/replace on the plaintext database file, replacing 'tonum(' with 'toint(' - take heed of the lack of a closing paren there.
